-- RUN THIS TO ADD THE NEW SOCIAL LINK COLUMNS TO YOUR DATABASE
ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS github text;
ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS linkedin text;
ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS email text;
